package org.aiwolf.liuchang;

public enum DataType {
	CO, DIVINED, TALKDIVINED, ID, VOTE, KILLED, EXECUTED, WILLVOTE, SKIP, DAYCHANGE, TURNSTART, GAMEEND, GAMESTART, WINNER, VOTESTART, MATCHSTART, ROLE
};
